apiVersion: v1
kind: Pod
metadata: 
  name: client-pod
  labels: 
    component: web
spec: 
  containers: 
    - name: client
      image: stephengrider/multi-worker 
      ports: 
        - containerPort: 9999 # changed the port from 3000 to 9999